### ISSUE TITLE
🍎 Feedback v38.0.0

### ISSUE THREAD

**Issue by found-sounds** [pulsedownloader/pulse-issues#1]
Event log:

```
Error: Firebase ID token has expired. Get a fresh token from your client app and try again (auth/id-token-expired). See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.
    at Client.req (/Applications/pulse.app/Contents/Resources/app.asar/src/api/index.ts:98:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by emmettcooke** [comment]
Hi please update to that latest version of Pulse (www.pulsedownloader.com) as this has been resolved now.

Apologies :)
