### ISSUE TITLE
🏁 Feedback v38.0.15

### ISSUE THREAD

**Issue by wobblefish** [pulsedownloader/pulse-issues#10]
Event log:

```
Error: HTTP 401 /putAnalytics?idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYTczOGUyMWI5MWNlMjRmNDM0ODBmZTZmZWU0MjU4Yzg0ZGI0YzUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHVsc2UtNjIyMjQiLCJhdWQiOiJwdWxzZS02MjIyNCIsImF1dGhfdGltZSI6MTU4Mzc5NTI2OCwidXNlcl9pZCI6ImFBVDNkWFYwQkdWUTVtQkRJY2tGaEV4WTlGQjMiLCJzdWIiOiJhQVQzZFhWMEJHVlE1bUJESWNrRmhFeFk5RkIzIiwiaWF0IjoxNTg1ODcxNDExLCJleHAiOjE1ODU4NzUwMTEsImVtYWlsIjoid29iYmxlZmlzaGR1YnNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIndvYmJsZWZpc2hkdWJzQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YRPhXGoQhpLs-egfeBc64LzTrgvM-gBAl1wiIwKWouCN8SU9q7HhOesFaGMen1OjAb4rCk7cyBDAZzI4cJLxlejsrRNHvK-wCVvwzNQvN4j5R62FgInk3AEjsYAul1T67K6Gme_XMtm_vSJ5RHBBU1_sllbtlQF3yUORSbe7XJ2D1EgC8OL-iyAOXOCX7ymIx3NQqhKpreD_usb5SHki0rRCdEczCjkajyUGAoSlfZ4m55eM0q57YSZeh9KyLriSzqZG-KmdQhBKJvO4JREUHyRS6zsABDGA-kU8l7RGoYyZ4NAwbROqHRr3HPWm_JgfOyBDOBcncyH0VL5j3MVj_A&redemptionKey=93129dba-5454-40a3-8698-872fd45b0044&type=downloading
    at Client.req (C:\Users\Wobblefish\AppData\Local\pulse\app-38.0.15\resources\app.asar\src\api\index.ts:92:19)
    at async Client.putAnalyticsDownloading (C:\Users\Wobblefish\AppData\Local\pulse\app-38.0.15\resources\app.asar\src\api\index.ts:171:16)
```

**Comment by wobblefish** [comment]
Issue was with Beta version. Re-ran setup for Pulse 38.0.17 and all is well.
