### ISSUE TITLE
🍎 Feedback v38.0.0

### ISSUE THREAD

**Issue by Beatsmithgomad** [pulsedownloader/pulse-issues#11]
Event log:

```
Error: HTTP 401 https://us-central1-pulse-62224.cloudfunctions.net/putAnalytics?idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYTczOGUyMWI5MWNlMjRmNDM0ODBmZTZmZWU0MjU4Yzg0ZGI0YzUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHVsc2UtNjIyMjQiLCJhdWQiOiJwdWxzZS02MjIyNCIsImF1dGhfdGltZSI6MTU3OTQ5MzkyNCwidXNlcl9pZCI6IlFQVjVxalgwSnJPdXgxdGc4dnJ0WnhiMU9UcDEiLCJzdWIiOiJRUFY1cWpYMEpyT3V4MXRnOHZydFp4YjFPVHAxIiwiaWF0IjoxNTg2MTQ5OTk2LCJleHAiOjE1ODYxNTM1OTYsImVtYWlsIjoiZ28xbWFkQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJnbzFtYWRAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Pw_nD_u0X4ztVJ7r-ErFQCK5u8SPb1TMWZDLinlcy3rpVHD3JusViyokyOzUzhB0Nar-ET2lxKHfCbVr7tfOXPZ0cSAYZZNI0Hy8lIaQwzCzR9oKTNlZy7SeHD23RiQHj7O7QXF8Maaq08BZfr9TAO7OBwRoypUEztKVbXlUiYZjHvA-szLzCRx4YLQaLtff6Vn5ipLScaT1J6Y6yQa0mq-cuPvBh71wVE-CwupcgJM1KLuha-EKeeJB3rrm-5NL27jRWuMut3xjvWlAmFW8X3Xhpj5u2xs4Dfv5Epn8hRea97pk2QzG9rEswi58DAu1UyCDx1rZI9RFz2tKZEstiQ&redemptionKey=4e968a2f-a7ef-43dc-88b7-d5b42d369bfb&type=downloading
    at Client.req (/Applications/pulse.app/Contents/Resources/app.asar/src/api/index.ts:101:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by megahertz** [comment]
@Beatsmithgomad It's fixed in the latest version v38.0.20
