### ISSUE TITLE
🏁 Feedback v38.0.24

### ISSUE THREAD

**Issue by osukakira** [pulsedownloader/pulse-issues#13]
Event log:

```
Error: Acceso denegado.

\\?\C:\Users\oscar\AppData\Local\Temp\b84946c7-b1af-4055-ba4b-6b45ec54ee48.tmp.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

**Comment by emmettcooke** [comment]
Hello could you please try this new version of Pulse and let us know if this works for you?

Windows: https://github.com/pulsedownloader/releases/releases/download/win32-x64-beta-40.0.0-beta.417/Pulse.Setup.40.0.0-beta.417.exe
Mac: https://github.com/pulsedownloader/releases/releases/download/darwin-x64-beta-40.0.0-beta.417/Pulse-40.0.0-beta.417.dmg

Thanks

**Comment by osukakira** [comment]
Good morning, it is solved, it is a compatibility problem, for those who have the same problem to run the troubleshooter in Windows 10, it works in compatibility on the Windows XP version. Thank you for your attention.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: emmettcooke<mailto:notifications@github.com>
Enviado: sábado, 18 de julio de 2020 03:51
Para: pulsedownloader/pulse-issues<mailto:pulse-issues@noreply.github.com>
CC: osukakira<mailto:oscar_urzagasti@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [pulsedownloader/pulse-issues] 🏁 Feedback v38.0.24 (#13)


Hello could you please try this new version of Pulse and let us know if this works for you?

Windows: https://github.com/pulsedownloader/releases/releases/download/win32-x64-beta-40.0.0-beta.417/Pulse.Setup.40.0.0-beta.417.exe
Mac: https://github.com/pulsedownloader/releases/releases/download/darwin-x64-beta-40.0.0-beta.417/Pulse-40.0.0-beta.417.dmg

Thanks

**Comment by emmettcooke** [comment]
Great thank you for letting us know.
