### ISSUE TITLE
Error in Pulse Pulse 40.0.0-beta.463

### ISSUE THREAD

**Issue by chaslea** [pulsedownloader/pulse-issues#14]
Comment (optional):

Error:
```
Error: spawn attrib ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

OS: Windows NT 10.0.18363

**Comment by emmettcooke** [comment]
Hello we have resolved this bug. Can you please close Pulse and install the new version from the website?
