### ISSUE TITLE
Error in Pulse Pulse 40.0.2

### ISSUE THREAD

**Issue by OmarUTG** [pulsedownloader/pulse-issues#15]
Comment (optional):

Error:
```
Error: ENOSPC: no space left on device, open '/Users/omarutg/Library/Application Support/Pulse/data/Lu5i3VEwFCSWZ3fOpvMlzhBobVx2/installations.json.1601528453963'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at ConfigFile.writeAtomic (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ConfigFile.js:56:8)
    at ConfigFile.write (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ConfigFile.js:45:14)
    at Config.writeData (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/Config.js:19:16)
    at Config.set (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/Config.js:63:10)
    at ElectronCfg.set (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ElectronCfg.js:47:17)
    at InstallationRepository.save (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/src/main/install/services/InstallationRepository.ts:43:1)
    at PulseRepository.saveInstallations (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/src/main/application/repository/PulseRepository.ts:64:1)
```

OS: macOS 10.15

**Comment by megahertz** [comment]
@OmarUTG There is no free disk space on your Mac. Try to free up some disk space and run Pulse again.
