### ISSUE TITLE
Error in Pulse Pulse 40.0.4

### ISSUE THREAD

**Issue by hydrazoan** [pulsedownloader/pulse-issues#17]
Comment (optional):

Error:
```
Error: spawn /Applications/Pulse.app/Contents/Resources/binaries/7z ENFILE
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

OS: macOS 10.14

**Comment by megahertz** [comment]
ENFILE error indicates that the system-wide limit on the total number of open files has been reached. So, restarting should solve the issue. Please let us know if it occurs again.
