### ISSUE TITLE
Error in Pulse Pulse 40.0.6

### ISSUE THREAD

**Issue by odhot** [pulsedownloader/pulse-issues#20]
Comment (optional):

Error:
```
Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

OS: macOS 10.14

**Comment by megahertz** [comment]
It was a temporary network issue. App should work fine when the connection established.
