### ISSUE TITLE
Error in Pulse Pulse 40.0.6

### ISSUE THREAD

**Issue by MilesMachina** [pulsedownloader/pulse-issues#21]
Comment (optional):

Error:
```
Error: sha512 checksum mismatch, expected whRuHjiJeJG8uqcEazWriCn8d0Tpg/Gn/Xie2D1vgLHLqWv12WB94wFsJJqvU63xD6lGFSwO7ZiTUDT0+2aHEg==, got qKwmlyPB/kcGmn2v44iHXLKpZqiiKdIcruMePUaLQKl62y9x2EnL4I0EFv0WkovB8/GK99XwkXbXSxi57upoeA==
    at newError (C:\Users\emilm\AppData\Local\Programs\pulse\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at DigestTransform.validate (C:\Users\emilm\AppData\Local\Programs\pulse\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:385:13)
    at DigestTransform._flush (C:\Users\emilm\AppData\Local\Programs\pulse\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:368:14)
    at DigestTransform.prefinish (_stream_transform.js:142:10)
    at DigestTransform.emit (events.js:315:20)
    at prefinish (_stream_writable.js:628:14)
    at finishMaybe (_stream_writable.js:636:5)
    at endWritable (_stream_writable.js:656:3)
    at DigestTransform.Writable.end (_stream_writable.js:595:5)
    at IncomingMessage.onend (_stream_readable.js:681:10)
```

OS: Windows NT 10.0.19042

**Comment by megahertz** [comment]
The error occurs when Pulse can't update itself to the latest version. Mostly it's a temporary error which could be ignored.
