### ISSUE TITLE
Error in Pulse Pulse 40.0.6

### ISSUE THREAD

**Issue by Jazzcraft** [pulsedownloader/pulse-issues#22]
Error:
```
Error: net::ERR_SSL_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

OS: Windows NT 10.0.19042

**Comment by megahertz** [comment]
Looks like a temporary network issue
