### ISSUE TITLE
Error in Pulse Pulse 40.0.6

### ISSUE THREAD

**Issue by moneycountaz** [pulsedownloader/pulse-issues#24]
Comment (optional):

Error:
```
Error: EBUSY: resource busy or locked, rename 'C:\Users\ctone\AppData\Roaming\Pulse\electron-cfg.json.1620760066499' -> 'C:\Users\ctone\AppData\Roaming\Pulse\electron-cfg.json'
    at Object.renameSync (fs.js:745:3)
    at ConfigFile.writeAtomic (C:\Users\ctone\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:57:8)
    at ConfigFile.write (C:\Users\ctone\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:45:14)
    at Config.writeData (C:\Users\ctone\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:19:16)
    at Config.set (C:\Users\ctone\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:63:10)
    at WindowManager.setState (C:\Users\ctone\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\WindowManager.js:134:16)
    at WindowManager.save (C:\Users\ctone\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\WindowManager.js:156:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

OS: Windows NT 10.0.19042

**Comment by megahertz** [comment]
It's fine when the issue appears only once. If it appears frequently, a system restart should solve the issue.
