### ISSUE TITLE
Error in Pulse Pulse 40.0.14

### ISSUE THREAD

**Issue by odhot** [pulsedownloader/pulse-issues#28]
Comment (optional):

Error:
```
Error: net::ERR_CONTENT_LENGTH_MISMATCH
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7029)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

OS: macOS 10.14

**Comment by megahertz** [comment]
It looks like a temporary network issue. Please let us know if it occurs again.
