### ISSUE TITLE
Error in Pulse Pulse 40.2.7

### ISSUE THREAD

**Issue by stewl** [pulsedownloader/pulse-issues#33]
Comment (optional):

Error:
```
UnhandledRejection Error: ESRCH, The system cannot find the path specified.
 'D:\PULSE items\Shreddage '
    at check (C:\Users\wstew\AppData\Local\Programs\pulse\resources\app.asar\node_modules\diskusage\index.js:23:21)
    at C:\Users\wstew\AppData\Local\Programs\pulse\resources\app.asar\node_modules\diskusage\index.js:10:5
    at new Promise (<anonymous>)
    at Object.exports.check (C:\Users\wstew\AppData\Local\Programs\pulse\resources\app.asar\node_modules\diskusage\index.js:9:10)
    at getFreeDiskSpaceViaDiskUsage (C:\Users\wstew\AppData\Local\Programs\pulse\resources\app.asar\dist\compiled\main\webpack:\pulse\src\main\utils\fs\getFreeDiskSpace.ts:33:1)
    at getFreeDiskSpace (C:\Users\wstew\AppData\Local\Programs\pulse\resources\app.asar\dist\compiled\main\webpack:\pulse\src\main\utils\fs\getFreeDiskSpace.ts:22:1)
    at DiskSpaceChecker.makeCheck (C:\Users\wstew\AppData\Local\Programs\pulse\resources\app.asar\dist\compiled\main\webpack:\pulse\src\main\install\utils\DiskSpaceChecker.ts:28:1)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

OS: Windows NT 10.0.19043

**Comment by megahertz** [comment]
Fixed in v40.2.8 
https://c8q9x5e9.map2.ssl.hwcdn.net/Pulse%20Web%20Setup%2040.2.8.exe
