### ISSUE TITLE
Error in Pulse Pulse 40.2.8

### ISSUE THREAD

**Issue by xentenza** [pulsedownloader/pulse-issues#34]
Comment (optional):

Error:
```
UnhandledRejection TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at DriveInfo.canContainFile (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getDriveInfo.ts:55:1)
    at /Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getDriveInfo.ts:128:1
    at Array.filter (<anonymous>)
    at getFreeDiskSpace (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getDriveInfo.ts:128:1)
    at DiskSpaceChecker.makeCheck (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/install/utils/DiskSpaceChecker.ts:30:1)
```

OS: macOS 10.13

**Comment by megahertz** [comment]
Fixed in v40.2.9 https://c8q9x5e9.map2.ssl.hwcdn.net/Pulse-40.2.9.dmg
