### ISSUE TITLE
Error in Pulse Pulse 40.3.2

### ISSUE THREAD

**Issue by seido6733** [pulsedownloader/pulse-issues#38]
Comment (optional):

Error:
```
UnhandledRejection Error: Can't find a drive for /Applications/Teletone Audio - Postcard Piano
    at getFreeDiskSpace (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/drive/getFreeDiskSpace.ts:32:1)
    at DiskSpaceChecker.makeCheck (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/install/utils/DiskSpaceChecker.ts:30:1)
```

OS: macOS 10.11

**Comment by megahertz** [comment]
Thank you. The fix will be released in v40.3.4.
