### ISSUE TITLE
Error in Pulse Pulse 40.3.4 

### ISSUE THREAD

**Issue by migfus** [pulsedownloader/pulse-issues#40]
Comment (optional):

Error:
```
Error: Product 22a5ad4e-005e-44a3-b3aa-d979d575c4be not found
    at Library.byId (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/src/renderer/store/product/Library.ts:26:1)
    at executeAction (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/mobx/dist/mobx.esm.js:1255:1)
    at Library.byId (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/mobx/dist/mobx.esm.js:1239:1)
    at Library.modifyProduct (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/src/renderer/store/product/Library.ts:145:1)
    at executeAction (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/mobx/dist/mobx.esm.js:1255:1)
    at Library.modifyProduct (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/mobx/dist/mobx.esm.js:1239:1)
    at RendererApi.markProductChanged (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/src/renderer/RendererApi.ts:39:1)
    at RpcServer.callHandler (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/electron-call/src/rpc/RpcServer.js:37:1)
    at file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/electron-call/src/rpc/RpcServer.js:26:1
    at IpcBus.onMessage (file:///C:/Users/migfus20/AppData/Local/Programs/pulse/resources/app.asar/dist/compiled/renderer/webpack:/pulse/node_modules/electron-call/src/IpcBus.js:40:1)
```

OS: Windows NT 10.0.22000

DON'T DO AN AUTOUPDATE!!! I'M CURRENTLY DOWNOADING LIBRARY AND THIS CAUSING AN ERROR RIGHT NOW

**Comment by megahertz** [comment]
Thank you for the report. It's fixed in v40.3.6 which will be published soon
