### ISSUE TITLE
Error in Pulse Pulse 40.3.22

### ISSUE THREAD

**Issue by IBNIAM** [pulsedownloader/pulse-issues#45]
Comment (optional):

Error:
```
Error: EPERM: operation not permitted, rename 'C:\Users\BoogieBeats\AppData\Roaming\Pulse\data\H9vtCdB3WZN1DuZU9ZDiJ9kkSl52\installations.json.1691902894977' -> 'C:\Users\BoogieBeats\AppData\Roaming\Pulse\data\H9vtCdB3WZN1DuZU9ZDiJ9kkSl52\installations.json'
    at Object.renameSync (node:fs:1030:3)
    at ConfigFile.writeAtomic (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:57:8)
    at ConfigFile.write (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:45:14)
    at Config.writeData (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:19:16)
    at Config.set (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:63:10)
    at ElectronCfg.set (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ElectronCfg.js:47:17)
    at InstallationRepository.save (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\dist\compiled\main\webpack:\pulse\src\main\install\services\InstallationRepository.ts:44:1)
    at PulseRepository.saveInstallations (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\dist\compiled\main\webpack:\pulse\src\main\application\repository\PulseRepository.ts:69:1)
    at EventBus.emit (node:events:525:35)
    at EventBus.emit (C:\Users\BoogieBeats\AppData\Local\Programs\pulse\resources\app.asar\dist\compiled\main\webpack:\pulse\src\main\application\EventBus.ts:18:1)
```

OS: Windows NT 10.0.19045

**Comment by IBNIAM** [comment]
?

**Comment by megahertz** [comment]
@IBNIAM Have you seen this error only once or it repeats from time to time? Did you finally install a product?
