### ISSUE TITLE
Error in Pulse Pulse 40.3.22

### ISSUE THREAD

**Issue by NLTRINI** [pulsedownloader/pulse-issues#49]
Comment (optional):

Error:
```
Error: Cannot execute Get-AuthenticodeSignature, stderr: Cannot invoke method. Method invocation is supported only on core types in this language mode.
At line:1 char:171
+ ... ch-Object { [Convert]::ToBase64String([System.Text.Encoding]::UTF8.Ge ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
 
. Failing signature validation due to unknown stderr.
    at handleError (C:\Users\navid\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-updater\src\windowsExecutableCodeSignatureVerifier.ts:130:11)
    at C:\Users\navid\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-updater\src\windowsExecutableCodeSignatureVerifier.ts:49:13
    at ChildProcess.exithandler (node:child_process:401:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

OS: Windows NT 10.0.19045

**Comment by megahertz** [comment]
Looks like the app can't be updated automatically from 40.3.22 to 40.4.0. We'll investigate the issue. Currently, it's possible to download the latest version from https://pulsedownloader.com/. You can check which version of Pulse is currently installed on the Settings page.
