### ISSUE TITLE
Error in Pulse Pulse 40.4.0

### ISSUE THREAD

**Issue by saleemus** [pulsedownloader/pulse-issues#50]
Comment (optional):

Error:
```
Error: EPERM: operation not permitted, rename 'C:\Users\User1\AppData\Roaming\Pulse\data\pZF9szYsFJQpYXnavNN6153MOg63\installations.json.1701001472482' -> 'C:\Users\User1\AppData\Roaming\Pulse\data\pZF9szYsFJQpYXnavNN6153MOg63\installations.json'
    at Object.renameSync (node:fs:1039:3)
    at ConfigFile.writeAtomic (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:57:8)
    at ConfigFile.write (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:45:14)
    at Config.writeData (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:19:16)
    at Config.set (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:63:10)
    at ElectronCfg.set (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ElectronCfg.js:47:17)
    at InstallationRepository.save (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\src\main\install\services\InstallationRepository.ts:44:29)
    at PulseRepository.saveInstallations (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\src\main\application\repository\PulseRepository.ts:69:26)
    at EventBus.emit (node:events:525:35)
    at EventBus.emit (C:\Users\User1\AppData\Local\Programs\pulse\resources\app.asar\src\main\application\EventBus.ts:18:18)
```

OS: Windows NT 10.0.19045

**Comment by saleemus** [comment]
I keep geting this message when i am trying to use Pulse.

**Comment by megahertz** [comment]
This problem should disappear after restarting Pulse

**Comment by saleemus** [comment]
> This problem should disappear after restarting Pulse

Unfortunately it doesn't. It happens everytime i open Pulse. I can install stuff, but i have to click to ignore this message  hundreds of times.

**Comment by megahertz** [comment]
Most probably, you have run Pulse as administrator, so now it can't write Pulse data files. There are two workarounds:
- Make sure your user account has full access to `C:\Users\User1\AppData\Roaming\Pulse\data\pZF9szYsFJQpYXnavNN6153MOg63` folder and to all files inside. [This instruction](https://www.windowscentral.com/how-take-ownership-files-and-folders-windows-10) could be helpful.
- Close Pulse and remove `C:\Users\User1\AppData\Roaming\Pulse`. When Pulse is restarted it recreates this directory. But login and product data will be lost, so you'll need to sign in and add installed products manually (Re-locate button on a product page).

**Comment by saleemus** [comment]
> Most probably, you have run Pulse as administrator, so now it can't write Pulse data files. There are two workarounds:
> 
>     * Make sure your user account has full access to `C:\Users\User1\AppData\Roaming\Pulse\data\pZF9szYsFJQpYXnavNN6153MOg63` folder and to all files inside. [This instruction](https://www.windowscentral.com/how-take-ownership-files-and-folders-windows-10) could be helpful.
> 
>     * Close Pulse and remove `C:\Users\User1\AppData\Roaming\Pulse`. When Pulse is restarted it recreates this directory. But login and product data will be lost, so you'll need to sign in and add installed products manually (Re-locate button on a product page).

Ok brilliant! I'll give this a try and let you know how i get on. Thanks and best wishes.

**Comment by saleemus** [comment]
> Most probably, you have run Pulse as administrator, so now it can't write Pulse data files. There are two workarounds:
> 
>     * Make sure your user account has full access to `C:\Users\User1\AppData\Roaming\Pulse\data\pZF9szYsFJQpYXnavNN6153MOg63` folder and to all files inside. [This instruction](https://www.windowscentral.com/how-take-ownership-files-and-folders-windows-10) could be helpful.
> 
>     * Close Pulse and remove `C:\Users\User1\AppData\Roaming\Pulse`. When Pulse is restarted it recreates this directory. But login and product data will be lost, so you'll need to sign in and add installed products manually (Re-locate button on a product page).

Hi there. Sorry for taking so long to get back to you. So i can't find the path from AppData, see attached screen shot
![ss1](https://github.com/pulsedownloader/pulse-issues/assets/152069999/5fa7fbe0-aab8-4672-82ce-bf373fcf7ed3)

**Comment by megahertz** [comment]
That folder is hidden. You can paste this path to the address bar and press Enter.
