### ISSUE TITLE
Error in Pulse Pulse 40.4.0

### ISSUE THREAD

**Issue by YKmack** [pulsedownloader/pulse-issues#51]
Comment (optional):

Error:
```
Error: ENOSPC: no space left on device, write
    at Object.writeSync (node:fs:933:3)
    at Object.writeFileSync (node:fs:2227:26)
    at ConfigFile.writeAtomic (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ConfigFile.js:56:8)
    at ConfigFile.write (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ConfigFile.js:45:14)
    at Config.writeData (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/Config.js:19:16)
    at Config.set (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/Config.js:63:10)
    at ElectronCfg.set (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ElectronCfg.js:47:17)
    at InstallationRepository.save (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/install/services/InstallationRepository.ts:44:29)
    at PulseRepository.saveInstallations (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/application/repository/PulseRepository.ts:69:26)
    at EventBus.emit (node:events:525:35)
```

OS: macOS 12

**Comment by megahertz** [comment]
"no space left on device" is why Pulse can't work correctly.
