### ISSUE TITLE
Error in Pulse Pulse 40.4.0

### ISSUE THREAD

**Issue by YKmack** [pulsedownloader/pulse-issues#52]
Comment (optional):

Error:
```
Error: ENOSPC: no space left on device, open '/Users/manuel/Library/Application Support/Pulse/data/dJODtZMfSCWmR5xFYs0IRe1OT0g1/installations.json.1701107692062'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at ConfigFile.writeAtomic (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ConfigFile.js:56:8)
    at ConfigFile.write (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ConfigFile.js:45:14)
    at Config.writeData (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/Config.js:19:16)
    at Config.set (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/Config.js:63:10)
    at ElectronCfg.set (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/electron-cfg/src/ElectronCfg.js:47:17)
    at InstallationRepository.save (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/install/services/InstallationRepository.ts:44:29)
    at PulseRepository.saveInstallations (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/application/repository/PulseRepository.ts:69:26)
```

OS: macOS 12

**Comment by megahertz** [comment]
"no space left on device" is why Pulse can't work correctly.
