### ISSUE TITLE
Error in Pulse Pulse 40.4.0

### ISSUE THREAD

**Issue by emker** [pulsedownloader/pulse-issues#53]
Comment (optional):
error during installation of a product downloaded by pulse

Error:
```
Error: EPERM: operation not permitted, rename 'C:\Users\user\AppData\Roaming\Pulse\data\vSDe0SzoiUhTFg1qsqyt0un3OV02\installations.json.1702623634364' -> 'C:\Users\user\AppData\Roaming\Pulse\data\vSDe0SzoiUhTFg1qsqyt0un3OV02\installations.json'
    at Object.renameSync (node:fs:1039:3)
    at ConfigFile.writeAtomic (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:57:8)
    at ConfigFile.write (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ConfigFile.js:45:14)
    at Config.writeData (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:19:16)
    at Config.set (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\Config.js:63:10)
    at ElectronCfg.set (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-cfg\src\ElectronCfg.js:47:17)
    at InstallationRepository.save (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\src\main\install\services\InstallationRepository.ts:44:29)
    at PulseRepository.saveInstallations (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\src\main\application\repository\PulseRepository.ts:69:26)
    at EventBus.emit (node:events:525:35)
    at EventBus.emit (C:\Users\user\AppData\Local\Programs\pulse\resources\app.asar\src\main\application\EventBus.ts:18:18)
```

OS: Windows NT 10.0.19045

**Comment by megahertz** [comment]
This issue is related to https://github.com/pulsedownloader/pulse-issues/issues/50. We're going to release a fix in two weeks.
