### ISSUE TITLE
Error in Pulse Pulse 40.4.0

### ISSUE THREAD

**Issue by Oldgit79** [pulsedownloader/pulse-issues#54]
Comment (optional):

Error:
```
Error: Cannot execute Get-AuthenticodeSignature, stderr: Cannot invoke method. Method invocation is supported only on core types in this language mode.
At line:1 char:171
+ ... ch-Object { [Convert]::ToBase64String([System.Text.Encoding]::UTF8.Ge ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
 
. Failing signature validation due to unknown stderr.
    at handleError (C:\Users\charl\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-updater\src\windowsExecutableCodeSignatureVerifier.ts:130:11)
    at C:\Users\charl\AppData\Local\Programs\pulse\resources\app.asar\node_modules\electron-updater\src\windowsExecutableCodeSignatureVerifier.ts:49:13
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

OS: Windows NT 10.0.22621

**Comment by Oldgit79** [comment]
What's all this about?

**Comment by megahertz** [comment]
Pulse can't be updated automatically. We'll going to make a new release soon where the issue is fixed.
