### ISSUE TITLE
Error in Pulse Pulse 40.4.12

### ISSUE THREAD

**Issue by milosnack** [pulsedownloader/pulse-issues#55]
Comment (optional):

Error:
```
Error: Can't save data files: ENOSPC: no space left on device, open '/Users/milozdalny/Library/Application Support/Pulse/data/TTeUNtSnk3XazZWPWwognA6gooX2/installations.json.1712866019461'
    at StorageFactory.handleSaveError (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/application/repository/StorageFactory.ts:31:13)
    at InstallationRepository.save (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/install/services/InstallationRepository.ts:47:27)
    at PulseRepository.saveInstallations (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/application/repository/PulseRepository.ts:69:26)
    at EventBus.emit (node:events:525:35)
    at EventBus.emit (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/application/EventBus.ts:18:18)
    at Installation2.eventWrapper (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/application/EventBus.ts:39:20)
    at ProgressMonitor.emitProgress (/Applications/Pulse.app/Contents/Resources/app.asar/src/main/install/models/ProgressMonitor.ts:69:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```

OS: macOS 11

**Comment by megahertz** [comment]
There isn't enough free disk space left.
