### ISSUE TITLE
Error in Pulse Pulse 40.4.16

### ISSUE THREAD

**Issue by TwigTone** [pulsedownloader/pulse-issues#58]
Comment (optional):

Error:
```
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:768:9)
    at Object.execFile (node:child_process:351:17)
    at Object.t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at Object.exec (node:child_process:236:25)
    at Object.exec (node:electron/js2c/asar_bundle:2:12711)
    at WindowsElevate (C:\Users\jbobh\AppData\Local\Programs\pulse\resources\app.asar\node_modules\@vscode\sudo-prompt\index.js:527:26)
    at C:\Users\jbobh\AppData\Local\Programs\pulse\resources\app.asar\node_modules\@vscode\sudo-prompt\index.js:491:19
    at C:\Users\jbobh\AppData\Local\Programs\pulse\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23)
```

OS: Windows NT 10.0.19045

**Comment by megahertz** [comment]
Most probably, that's related to some Antivirus software. Did it happen only once?

**Comment by TwigTone** [comment]
> Most probably, that's related to some Antivirus software. Did it happen only once?

I honestly should have thought of that before, just ran as admin and it worked.

Thank you!
