### ISSUE TITLE
Error in Pulse Pulse 40.4.18

### ISSUE THREAD

**Issue by NumberTwo2** [pulsedownloader/pulse-issues#59]
Comment (optional):

Error:
```
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:768:9)
    at Object.execFile (node:child_process:351:17)
    at Object.t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at Object.exec (node:child_process:236:25)
    at Object.exec (node:electron/js2c/asar_bundle:2:12711)
    at WindowsElevate (C:\Users\cnugg\AppData\Local\Programs\pulse\resources\app.asar\node_modules\@vscode\sudo-prompt\index.js:527:26)
    at C:\Users\cnugg\AppData\Local\Programs\pulse\resources\app.asar\node_modules\@vscode\sudo-prompt\index.js:491:19
    at C:\Users\cnugg\AppData\Local\Programs\pulse\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23)
```

OS: Windows NT 10.0.22631

**Comment by megahertz** [comment]
Most probably, that's related to some Antivirus software.
